### ISSUE TITLE
Facebook Auth

### ISSUE THREAD

**Issue by froyolo** [move-around/MoveAround#20]
Add Facebook connect and store the user details in Parse

**Comment by elg0nz** [comment]
Done. The current user is now located at User.current user and the ParseUser on PFUser.current()

**Comment by froyolo** [comment]
I'm getting an error message when I log in.  Is there something special I need to do?

![img_3247](https://user-images.githubusercontent.com/7277087/31857273-f14e028a-b68e-11e7-9732-fea982641eb6.PNG)

**Comment by elg0nz** [comment]
@froyolo I've made the add public and added you two as administrators. It should work now
