### ISSUE TITLE
A location should only be allowed to be added once to an itinerary

### ISSUE THREAD

**Issue by froyolo** [move-around/MoveAround#22]
It's probably rare that a user would want to go to the same place twice on the same day.  For now, don't allow the user to add the same place multiple times in the itinerary (on the same day).  

![img_2057d793e10e-1](https://user-images.githubusercontent.com/7277087/31854960-d3d71f4a-b655-11e7-8c2a-6eb578c4f2aa.jpeg)

**Comment by tanejamohit** [comment]
Fixed
