### ISSUE TITLE
User Preferences

### ISSUE THREAD

**Issue by elg0nz** [move-around/MoveAround#6]
- [x] User story Description
In user preferences, we want to the user to be able to change the destination city and the dates they are planning for their visit.

- [x] Screenshots of similar apps

This is what Airbnb does for the same
![img_3414](https://user-images.githubusercontent.com/4754241/31319452-89da9ef4-ac18-11e7-9762-f6771f995174.PNG)

**Comment by tanejamohit** [comment]
I think this might be good for now, but we would have to come back to this and dig deeper into what we want the user to be able to change here.
